### ISSUE TITLE
org.springframework.data.ebean.domain.AbstractAggregateRoot怎么用

### ISSUE THREAD

**Issue by craftsman-li** [hexagonframework/spring-boot-data-ebean-samples#1]
以前光看没用过ddd，这个到底该咋用？能在例子里体现吗？

**Comment by yuanxuegui** [comment]
spring-data-ebean的AbstractAggregateRoot有注册领域事件的功能，基于spring的Event实现，在仓储保存聚合根的时候会自动发送Event，触发Event监听器的处理。例子可参见spring-data-ebean的单元测试:
[User](https://github.com/hexagonframework/spring-data-ebean/blob/master/src/test/java/org/springframework/data/ebean/sample/domain/User.java)
[UserDomainService.java](https://github.com/hexagonframework/spring-data-ebean/blob/master/src/test/java/org/springframework/data/ebean/sample/domain/UserDomainService.java)
[UserRepositoryIntegrationTest.testDomainEvent](https://github.com/hexagonframework/spring-data-ebean/blob/master/src/test/java/org/springframework/data/ebean/repository/UserRepositoryIntegrationTest.java)
